# Generated by Django 3.1.7 on 2021-03-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user_id',
        ),
    ]
